name: Hostel
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.4.0
  dartz: ^0.8.6
  flutter_bloc: ^0.21.0
  get_it: ^2.0.1
  shared_preferences: ^0.5.4+4
  connectivity: ^0.4.3+7
  http: ^0.12.0+2
  url_launcher: ^5.7.5

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.14.0+5
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  flutter_launcher_icons: "^0.8.0"

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"

flutter:

  uses-material-design: true
  assets:
    - assets/My_pic.jpeg
    - assets/logo.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
