name: Hostel
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^1.2.6
  dartz: ^0.9.2
  url_launcher: ^5.7.10
  flutter_spinkit: ^4.1.2
  google_fonts: ^1.1.2
  flutter_bloc: ^6.1.3
  firebase_core: ^0.7.0
  firebase: ^8.0.0

  cupertino_icons: ^0.1.2
  firebase_auth: 
  cloud_firestore: 
  provider: ^4.3.2+3
  flex_color_scheme:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  flutter_launcher_icons: "^0.8.0"

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"

flutter:

  uses-material-design: true
  assets:
    - assets/My_pic.jpeg
    - assets/logo.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
